name: nop_gen
description: route generator for flutter_nop plugin
version: 0.3.2
repository: https://github.com/sersr/nop_gen

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  source_gen: ">=1.2.2"
  analyzer: "^6.9.0"
  build:
  nop_annotations: ">=0.3.2"

dev_dependencies:
  test: ^1.16.4
  build_runner: any
  lints: ^2.0.0

dependency_overrides:
  nop_annotations:
    path: ../nop_annotations